### ISSUE TITLE
PDO Connection from within Flight

### ISSUE THREAD

**Issue by JustSteveKing** [mikecao/sparrow#14]
Hey, Just trying to figure out how your DB class is working here - it seems pretty awesome so far, however I have a few questions.

I have managed to get this working within Flight with no problems by doing the following : 
   `Flight::register("db", "flight\services\Sparrow");`
    `Flight::db()->setDb(array(" /* Connection information in here */ "));`

However my question is, with Sparrow how do we set our own parameters for the PDO connection? I don't know if it is just me bust I like to use `PDO_FETCH_OBJ` where I can as I find it easier to work with.

Anyway, thanks for the awesome class! Keep up the great work

**Comment by mikecao** [comment]
Just use the `getDb` method. It will return the original database object.
