### ISSUE TITLE
mysql_* functions are depreciated and will be removed in future.

### ISSUE THREAD

**Issue by givik** [mikecao/sparrow#19]
Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in Sparrow.php on line 622.

**Comment by mikecao** [comment]
Sparrow supports both mysqli and PDO already. Just use whatever is available on your system. The original mysql functions are there to support older systems.

**Comment by givik** [comment]
Thanks. I see :+1:
